[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["mvn -DskipTests clean package"]

[start]
cmd = "java -Xmx256m -XX:MaxMetaspaceSize=128m -XX:+UseSerialGC -XX:TieredStopAtLevel=1 -jar target/scalora-api-1.0.0.jar"
